// Vue/template/snowpack-vue-ts/src/container/Main.vue
<template>
    <div class="container">
        <div>Main</div>
        <div class="go-page" @click="goPage('/pageI')">Go PageI</div>
        <div class="go-page" @click="goPage('/pageII')">Go PageII</div>
        <div class="open-modal-btn" @click="toggleModalStatus(true)">Open Modal !</div>
        <div class="route-container">
            Route Area
            <router-view />
        </div>
        <Modal :toggleModal="toggleModal" @toggleModalStatus="toggleModalStatus" />
    </div>
</template>
<style lang="scss" scoped>
.container{
    .go-page,
    .open-modal-btn{
        box-shadow: 0 0 2px 0 rgba(30,30,30,.5);
        width: 100px;
        text-align: center;
        padding: 5px;
        border-radius: 5px;
        cursor: pointer;
        user-select: none;
    }
    .route-container{
        background-color: blue;
        color: white;
        width: 300px;
        padding: 5px;
        border-radius: 5px;
        box-shadow: 0 0 2px 0 rgba(30,30,30,.5);
    }
}
</style>
<script lang="ts">
import { defineComponent,Ref,ref } from 'vue'
import { useRouter } from 'vue-router'
import Modal from '../component/Modal.vue'

interface stateType {
    toggleModal:Ref<boolean>
}

interface methodType {
    goPage(path:string):void
    toggleModalStatus(status:boolean):void
}

export default defineComponent({
    components:{
        Modal
    },
    setup(){
        const router = useRouter()

        const state:stateType = {
            toggleModal:ref(false)
        }

        const method:methodType = {
            goPage:path => router.push(path),
            toggleModalStatus:status => state.toggleModal.value = status
        }
        
        return { ...state,...method }
    }
})
</script>

// Svelte/template/parcel-svelte-ts/src/container/Main.svelte
<div>
    mains
    {num}
    <div class="go-page-btn" on:click={goPage.bind(undefined,'Page_I')}>Go PageI</div>
    <div class="go-page-btn" on:click={goPage.bind(undefined,'Page_II')}>Go PageII</div>
    <div class="routes">
        <div class="title">Route Layout</div>
        <Viewport {router} />
    </div>
</div>
<style lang="scss" scoped>
    .routes{
        .title{
            margin-bottom: 10px;
            font-size: 20px;
        }
        margin: 10px 0;
        padding: 5px 10px;
        background-color: blue;
        border-radius: 5px;
        width: 50%;
        color: white;
    }
    .go-page-btn{
        padding: 5px 0;
        width: 100px;
        text-align: center;
        background-color: black;
        border-radius: 5px;
        color: white;
        cursor: pointer;
        user-select: none;
        &:nth-of-type(1){
            margin-bottom: 5px;
        }
    }
</style>
<script lang="ts">
    export let num:number | undefined = 99
    import { Viewport } from '@danielsharkov/svelte-router/src/'
    import router from '../router'

    const goPage:(pathName:string) => void = pathName => {
        if(pathName === 'pageII'){
            router.push(pathName,undefined,{ a:9999 } as any)
        } else {
            router.push(pathName,{ a:10 } as any,{ a:20 } as any)
        }
        
    }
</script>
