// Svelte/template/esbuild-svelte-ts/src/App.svelte
<!-- svelte-ignore a11y-click-events-have-key-events -->
<template lang="pug">
    .container
        h1 Hello Svelte & Esbuild !
        .count(class="{toggleColor ? 'toggle' : ''}") {count}
        |{ count }{ (count % 2) !== 0 ? ' is odd number' : " is't odd number" }
        br
        |{ count }{ (count % 2) === 0 ? ' is even number' : " is't even number" }
        Main(isColorChange="{toggleColor}")
        .add-btn(on:click="{addCount}") AddCount
</template>
<style lang="scss">
    .container{
        h1{
            color: red;
        }
        .count{
            color: red;
            transition: .5s ease;

            &.toggle{
                color: blue;
            }
        }
    }
</style>
<script lang="ts">
import Main from './Main.svelte'

let count:number = 0
let toggleColor:boolean = false

const addCount:() => void = () => {
    count++
    toggleColor = !toggleColor
}
</script>

// Vue/template/rollup-vue-ts/src/App.vue
<template>
    <div class="container">
        Hello Vue & Rollup !
        <div class="sd">aaaaa</div>
        <div class="count-text" :class="{ active:toggleClass }">{{ count }}</div>
        <div @click="addCount">Click</div>
    </div>
</template>
<style lang="scss" scoped>
    .container{
        color: red;
        .sd{
            color: blue;
        }
        .count-text{
            transition: .5s ease;

            &.active{
                color: blue;
            }
        }
    }
</style>
<script lang="ts">
import { defineComponent,Ref,ref } from 'vue'

interface stateType {
    count:Ref<number>
    toggleClass:Ref<boolean>
}

interface methodType {
    addCount():void
}

export default defineComponent({
    setup(){
        const state:stateType = {
            count:ref(0),
            toggleClass:ref(false)
        }

        const method:methodType = {
            addCount:() => {
                state.count.value++
                state.toggleClass.value = !state.toggleClass.value
            }
        }

        return { ...state,...method }
    }    
})
</script>
