// Vue/template/snowpack-vue-ts/src/component/Modal.vue
<template>
    <div class="modal-outer" :class="{ 'active': toggleModal }">
        <div class="modal">
            <div class="modal-body">Hello !</div>
            <div class="modal-footer">
                <div @click="useToggleModalStatus">Cancel</div>
                <div @click="useToggleModalStatus">Confirm</div>
            </div>
        </div>
    </div>
</template>
<style lang="scss" scoped>
    .modal-outer{
        position: fixed;
        top: 0;
        right: 0;
        left: 0;
        bottom: 0;
        background-color: rgba(30,30,30,.5);
        backdrop-filter: blur(10px);
        opacity: 0;
        z-index: -1;
        transition: .5s ease;

        .modal{
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%,-50%);
            width: 300px;
            max-width: 95%;
            background-color: white;
            border-radius: 5px;

            .modal-body{
                padding: 10px;
            }
            .modal-footer{
                display: flex;
                div{
                    width: 50%;
                    cursor: pointer;
                    user-select: none;
                    padding: 5px;
                    font-weight: bold;
                    text-align: center;
                }
            }
        }

        &.active{
            opacity: 1;
            z-index: 5;
        }
    }
</style>
<script lang="ts">
import { defineComponent, toRefs } from 'vue'

interface methodType {
    useToggleModalStatus():void
}

export default defineComponent({
    props:["toggleModal"],
    emits:["toggleModalStatus"],
    setup(props,{ emit }){
        
        const method:methodType = {
            useToggleModalStatus:() => emit('toggleModalStatus',false) 
        }

        return { ...toRefs(props), ...method }
    }
})
</script>

// Svelte/template/rollup-svelte-ts/src/component/Modal/Modal.svelte
<div class={ toggleModal ? "modal-outer toggle-modal" : "modal-outer"}>
    <div class="modal">
        <div class="modal-body">
            <slot name="line-1" />
            <slot />
        </div>
        <div class="modal-footer">
            <div class="comfirm">Confirm</div>
            <div class="cancle" on:click={setModalToggleProps}>Cancle</div>
        </div>
    </div>
</div>
<style lang="scss" scoped>
    .modal-outer{
        position: fixed;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        background-color: rgba(0,0,0,.7);
        opacity: 0;
        z-index: -1;
        transition: .7s ease;
        .modal{
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%,-50%);
            width: 100%;
            max-width: 400px;
            .modal-body{
                background-color: white;
                padding: 12px;
            }
        }
        &.toggle-modal{
            opacity: 1;
            z-index: 1;
        }
    }
</style>
<script lang="ts">
    export let toggleModal:boolean = false

    // like react
    export let setModalToggle:(status:boolean) => void = () => undefined;
    export let setModalToggleProps:() => void = () => setModalToggle(false)

    // like vue
    // import { createEventDispatcher } from 'svelte'
    // const emite = createEventDispatcher()
    // const setModalToggleProps:() => void = () => emite('setModalToggle',false)
</script>
