// React/movies/src/component/Pagination/Pagination.tsx
import { FunctionComponent } from "react";
import { PaginationProps,paginationObjType,cssSetPropertys } from './types'
import styles from './styles'

const { Show }: cssSetPropertys = styles

const Pagination:FunctionComponent<PaginationProps> = ({ paginationObjProps }:PaginationProps):JSX.Element => {

    const {
        hasPrev,
        hasNext,
        currentPage,
        totalLength,
        partPage,
        pageTotal,
        pageSize,
        postNext
    }:paginationObjType = paginationObjProps

    const current:Function = (currentPage:number,e:Event):void => {
        e.preventDefault()
        postNext(currentPage)
    }

    const renderPage:Function = ():JSX.Element[] => {
        let pageTotalToArray:number[] = []

        if (paginationObjProps !== undefined) {
            if (currentPage <= pageTotal) {
              if (currentPage < pageSize) {
                //當前頁數小於總頁數
                let i = Math.min(pageSize!, pageTotal);
                while (i) {
                  pageTotalToArray = [i--, ...pageTotalToArray]
                }
              } else {
                //當前頁數大於顯示總頁數
                let middle = currentPage - Math.floor(pageSize / 2)
                //記錄起始位置
                let i = pageSize;
                if (middle > pageTotal - pageSize) {
                  middle = pageTotal - pageSize! + 1;
                }
                while (i--) {
                  pageTotalToArray = [...pageTotalToArray, middle++]
                }
              }
            }
        }

        return (
            pageTotalToArray.map((pages:number,index:number) => (
                <li className="page-item" key={index}>
                    {
                        // eslint-disable-next-line jsx-a11y/anchor-is-valid
                        <a className={currentPage === pages ? "page-link active" : "page-link"} href="#" onClick={current.bind(this,pages)}>{pages}</a>
                    }
                </li>)
            )
        )

    }

    return (
        <Show>
            <nav className="pagination-outer" aria-label="Page navigation">
                <ul className="pagination justify-content-center align-items-center">
                    <li className={!hasPrev ? "page-item disabled" : "page-item"}>
                        <a className={hasPrev ? "page-link page-link-active" : "page-link"} href="/#" onClick={current.bind(this,currentPage - 1)}>
                            <span aria-hidden="true"><i className="far fa-chevron-double-left"></i></span>
                        </a>
                    </li>
                    {renderPage()}
                    <li className={!hasNext ? "page-item disabled" : "page-item"}>
                        <a className={hasNext ? "page-link page-link-active" : "page-link"} href="/#" onClick={current.bind(this,currentPage + 1)}>
                            <span aria-hidden="true"><i className="far fa-chevron-double-right"></i></span>
                        </a>
                    </li>
                </ul>
            </nav>
        </Show>
    )
}

export default Pagination

// Angular/hotels_origin/src/app/component/pagination/pagination.component.ts
import { Component, Input, OnChanges, OnInit, Output, EventEmitter } from '@angular/core';
import { paginationType } from '../../types/types'

@Component({
  selector: 'app-pagination',
  templateUrl: './pagination.component.html',
  styleUrls: ['./pagination.component.scss']
})
export class PaginationComponent implements OnInit, OnChanges {
  @Input()
  public paginationObjProps: paginationType = {
    totalLength: 0,
    partPage: 0,
    pageTotal: 0,
    pageTotalToArray: [],
    currentPage: 1,
    hasPrev: false,
    hasNext: true,
    pageSize: 0
  }
  @Output()
  public goCurrent: EventEmitter<{ pages: number | undefined, partPage: number, pageSize: number }> = new EventEmitter()
  constructor() { }

  ngOnInit() {
  }

  ngOnChanges() {
    if (this.paginationObjProps != undefined) {
      if (this.paginationObjProps.currentPage <= this.paginationObjProps.pageTotal) {
        if (this.paginationObjProps.currentPage < this.paginationObjProps.pageSize) {
          //當前頁數小於總頁數
          let i = Math.min(this.paginationObjProps.pageSize, this.paginationObjProps.pageTotal);
          while (i) {
            this.paginationObjProps.pageTotalToArray = [i--, ...this.paginationObjProps.pageTotalToArray]
          }
        } else {
          //當前頁數大於顯示總頁數
          let middle = this.paginationObjProps.currentPage - Math.floor(this.paginationObjProps.pageSize / 2),
            //記錄起始位置
            i = this.paginationObjProps.pageSize;
          if (middle > this.paginationObjProps.pageTotal - this.paginationObjProps.pageSize) {
            middle = this.paginationObjProps.pageTotal - this.paginationObjProps.pageSize + 1;
          }
          while (i--) {
            this.paginationObjProps.pageTotalToArray = [...this.paginationObjProps.pageTotalToArray, middle++]
          }
        }
      }
    }
  }

  current(event: Event, pages: number) {
    event.preventDefault()
    let { partPage, pageSize } = this.paginationObjProps
    this.goCurrent.emit({ pages: pages, partPage: partPage, pageSize: pageSize })
  }
}

<nav class="pagination-outer" aria-label="Page navigation">
  <ul class="pagination justify-content-center align-items-center">
      <li class="page-item" [class.disabled]="!paginationObjProps.hasPrev">
          <a class="page-link" [class.page-link-active]="paginationObjProps.hasPrev" href="/#" (click)="current($event,paginationObjProps.currentPage - 1)">
              <span aria-hidden="true"><i class="far fa-chevron-double-left"></i></span>
          </a>
      </li>
      <li
        class="page-item"
        *ngFor="let pages of paginationObjProps.pageTotalToArray"
      >
        <a class="page-link" [class.active]="paginationObjProps.currentPage == pages" href="#" (click)="current($event,pages)">{{ pages }}</a>
      </li>
      <li class="page-item" [class.disabled]="!paginationObjProps.hasNext">
        <a class="page-link" [class.page-link-active]="paginationObjProps.hasNext" href="/#" (click)="current($event,paginationObjProps.currentPage + 1)">
            <span aria-hidden="true"><i class="far fa-chevron-double-right"></i></span>
        </a>
      </li>
  </ul>
</nav>
