// Vue/stars-pwa-ts/src/components/Toast/Toast.vue
<template lang="pug">
    teleport(to="#app")
       Transition(name="toggle")
           template(v-if="toggleToastStatus")
               .toast-outer
                    template(v-if="iconStatus ? true : false")
                        .icon
                            template(v-if="iconStatus === 'success'")
                                i.fas.fa-check-circle.success
                            template(v-if="iconStatus === 'info'")
                                i.fas.fa-info-circle.info
                            template(v-if="iconStatus === 'error'")
                                i.fas.fa-times-circle.error
                    div {{ toastText }}

</template>
<style lang="scss" scoped>

   .toast-outer {
       position: fixed;
       top: 0;
       left: 0;
       right: 0;
       z-index: 500;
       background-color: rgba(30,30,30,.5);
       backdrop-filter: blur(10px);
       -webkit-backdrop-filter: blur(10px);
       margin: 12px;
       border-radius: 5px;
       box-shadow: 0 0 0 .5px rgba(255,255,255,.7);

       .icon {
        position: absolute;
        top: 50%;
        left: 0;
        transform: translateY(-50%);
        margin-left: 16px;

        .success {
            color: rgb(0,221,0);
        }

        .info {
            color: rgb(0,187,255);
        }

        .error {
            color: rgb(255,51,51);
        }
       }

       div {
        padding: 12px 0;
        text-align: center;
       }
   }

   .toggle-enter-active,
   .toggle-leave-active {
       transition: opacity .5s ease, transform .5s ease;
   }

   .toggle-enter-from,
   .toggle-leave-to {
       opacity: 0;
       transform: translateY(-100%);
   }
</style>
<script lang="ts">
import { defineComponent, toRefs } from 'vue'

export default defineComponent({
    props:['toggleToastStatus', 'toastText', 'iconStatus'],
    setup(props: { toggleToastStatus: boolean, toastText: string, iconStatus?: string }){

        const propsRefs = toRefs(props)

        return { ...propsRefs }
    }
})

</script>

// Svelte/Shard-Server-CSR/client/src/component/Toast.svelte
<div class="toast-outer-frame" bind:this={toastOuterFrameRef}></div>
<style lang="scss">
    .toast-outer-frame {
        position: fixed;
        top: 0;
        left: 50%;
        transform: translateX(-50%);
        width: 95%;
        max-width: 385px;
        z-index: 1000;

        :global(.toast-message-box){
            position: relative;
            margin: 6px;
            opacity: 0;
            transform: translateY(-100%) scale(.5);
            color: white;
            backdrop-filter: blur(10px);
            box-shadow: 0 0 2px 0px rgba(255, 255, 255, .5);
            padding: 12px;
            border-radius: 5px;
            background-color: rgba(30, 30, 30, .5);
            display: grid;
            grid-template-columns: 0fr 1fr;
            gap: 8px;
            align-items: center;
        }

        :global(.toast-message-box .box-text){
            text-align: center;
            word-break: break-word;
            white-space: pre-line;
        }

        :global(.toast-message-box svg.success){
            color: rgb(0,221,0);
            font-size: 20px;
        }

        :global(.toast-message-box svg.error){
            color: rgb(255,51,51);
            font-size: 20px;
        }

        :global(.toast-message-box svg.info){
            color: rgb(0,221,221);
            font-size: 20px;
        }
    }
</style>
<script lang="ts">

    import { 
        faCheckCircle,
        faXmarkCircle,
        faExclamationCircle,
    } from '@fortawesome/free-solid-svg-icons';
    import FontAwesomeIcon from 'svelte-fa';
    import { mount } from 'svelte'

    let { toastMessages = { message: '', status: '' }, duration = 0 } = $props()

    let toastBoxIndex: number = 0

    let toastOuterFrameRef = $state<HTMLDivElement | undefined>(undefined)
    
    const sleep:(time: number) => Promise<void> = async time => 
        await new Promise(resovle => setTimeout(() => resovle() ,time))

    const createDom: () => Promise<void> = async () => {

        if(!toastOuterFrameRef || toastMessages.message === '') return

        const signIcon:Record<string, any> = {
            'success': faCheckCircle,
            'error': faXmarkCircle,
            'info': faExclamationCircle
        }

        toastBoxIndex += 1

        const toastMessageBox = document.createElement('div')

        const toastMessageBoxText = document.createElement('div')

        toastMessageBoxText.textContent = toastMessages.message

        toastMessageBoxText.className = 'box-text'

        toastMessageBox.className = 'toast-message-box'

        toastMessageBox.style.cssText = `z-index:${toastBoxIndex};`

        toastMessageBox.animate(
            { transform: 'translateY(0%) scale(1)', opacity: 1 }, 
            { duration: 400, fill: 'forwards', easing: 'ease' }
        )

        mount(FontAwesomeIcon, {
            target: toastMessageBox,
            props: { icon: signIcon[toastMessages.status], class: toastMessages.status }
        })

        toastMessageBox.appendChild(toastMessageBoxText)

        toastOuterFrameRef.prepend(toastMessageBox)

        await sleep(duration)

        toastMessageBox.animate(
            { transform: 'translateY(-100%) scale(.5)', opacity: 0 }, 
            { duration: 400, fill: 'forwards', easing: 'ease' }
        )

        await sleep(duration)

        toastMessageBox.remove()
    }


    $effect(() => {
        createDom()
    })

</script>
